export PATH=$PWD:$PATH
export PYTHONPATH=$PWD:$PYTHONPATH
export PYTHONPATH=$PWD/dftbtorch:$PYTHONPATH
export PYTHONPATH=$PWD/DFTBMaLT:$PYTHONPATH
#export PYTHONPATH=$PWD/DFTBMaLT/dftbmalt:$PYTHONPATH
