export PATH=$PWD:$PATH
export PYTHONPATH=$PWD:$PYTHONPATH
#export PATH=$PWD/dftbtorch:$PYTHONPATH
export PYTHONPATH=$PWD/DFTBMaLT:$PYTHONPATH

# CCS
export PYTHONPATH=$PWD/utils/CCS:$PYTHONPATH
export PATH=$PWD/utils/CCS/bin:$PATH
